version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-prod:/var/lib/mysql-data-prod
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - network-production # Nama jaringan yang sama dengan jaringan aplikasi

  casheer-app:
    image: 'prod-casheer-be-image:latest'
    # volumes:
    #   - ./assets:/app/assets
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    restart: on-failure
    networks:
      - network-production # Nama jaringan yang sama dengan jaringan MySQL

networks:
  network-production:
    # Nama jaringan yang sama dengan jaringan MySQL
    driver: bridge # Anda dapat menggunakan driver jaringan yang sesuai dengan kebutuhan Anda

volumes:
  mysql-data-prod:
