version: '3'
services:
  mysql:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db_prod_casheer
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  casheer-app:
    image: 'prod-casheer-be-image:latest'
    # volumes:
    #   - ./assets:/app/assets
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3309
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: db_prod_casheer
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    restart: on-failure

volumes:
  mysql-data:
